filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/jenkins/jenkins.log
    fields:
      service: jenkins
      environment: production
    fields_under_root: true
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2}' # Match log lines starting with a date
      negate: true
      match: after

output.logstash:
  hosts: ["<LOGSTASH_SERVER_IP>:5044"]

setup.kibana:
  host: "<KIBANA_SERVER_IP>:5601"

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

